<?php

namespace Keky\Product\Tests;

use Keky\Product\ProductModuleServiceProvider;
use Orchestra\Testbench\TestCase as Orchestra;

class TestCase extends Orchestra
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        // Include the custom service provider
        return [
            ProductModuleServiceProvider::class,
        ];
    }
}
