<?php

namespace Keky\Product\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Validation\Rule;
use Keky\Product\Enums\Currency;
use Keky\Product\Enums\ProductStatus;
use Keky\Product\Enums\ProductUnit;
use Keky\Product\Models\Product;

class ProductRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'title' => ['required', 'string'],
            'subtitle' => ['sometimes', 'required', 'string'],
            'description' => ['sometimes', 'required', 'string'],
            'slug' => ['sometimes', 'required', 'string', Rule::unique(Product::class, 'id')->ignore(request()->route('id'))],
            'status' => ['sometimes', 'required', Rule::enum(ProductStatus::class)],
            'thumbnail' => ['sometimes', 'required', 'string'],
            'price' => ['sometimes', 'required', 'numeric'],
            'buy_price' => ['sometimes', 'required', 'numeric'],
            'sku' => ['sometimes', 'required', 'string', Rule::unique(Product::class, 'sku')->ignore(request()->route('id'))],
            'unit' => ['sometimes', 'required', Rule::enum(ProductUnit::class)],
            'currency' => ['sometimes', 'required', Rule::enum(Currency::class)],
            'weight' => ['sometimes', 'required', 'numeric'],
            'height' => ['sometimes', 'required', 'numeric'],
            'width' => ['sometimes', 'required', 'numeric'],
            'type_id' => ['sometimes', 'required', 'string'],
            'metadata' => ['sometimes', 'required', 'json'],
        ];
    }

    public function failedValidation(Validator $validator)
    {
        // parent::failedValidation($validator); // TODO: Change the autogenerated stub
        throw new HttpResponseException(
            response()->json(
                [
                    'status' => 'failed',
                    'message' => 'Something went wrong',
                    'errors' => $validator->errors(),
                ],
                422
            ));
    }
}
